services:

  web:    
    build: .
    command: ["python", "src/gos/manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - src/gos/.env
  
  db:
    image: postgres:13
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/ 
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db_name
    ports:
      - 5432:5432      
      # by default postgres listens on 5432

  db_test:
    image: postgres:13
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - 5433:5432  # Map port 5433 on the host to port 5432 in the container for the test database
    command: -p 5433

# Configure a volume to persist the data beyond the life of the container
volumes:
  postgres_data_dev: